apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
      - name: portfolio-website
        image: ghcr.io/np22-jpg/website:latest
        ports:
        - containerPort: 8080