apiVersion: v1
kind: Service
metadata:
  name: portfolio-website
spec:
  type: ClusterIP
  selector:
    app: portfolio-website
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080