name: Build and Push to GHCR

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *" # Run once every day

env:
  REPO: website
  PLATFORMS: linux/amd64

jobs:
  build_and_push_docker_images:
    name: Push Docker image to GHCR
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build Production Images
        id: build-image
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3
        with:
          image: website
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      # PUSH

      - name: Push To GHCR
        if: github.event_name != 'pull_request'
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}

      # SIGN
      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        if: github.event_name != 'pull_request'
      
      - name: Sign GHCR Image
        if: github.event_name != 'pull_request'
        run: |
          cosign login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}@${GHCR_TAGS}
        env:
          COSIGN_EXPERIMENTAL: false
          GHCR_TAGS: ${{ steps.push-to-ghcr.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Print image URLs
        if: github.event_name != 'pull_request'
        run: |
          echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"