name: Scan with Trivy

on:
  workflow_run:
    workflows: ["Build and Push to Docker Hub"]
    types:
      - completed

jobs:
  scan:
    name: Scan Images

    permissions:
      security-events: write
      packages: read

    runs-on: ubuntu-latest
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # master
      with:
        image-ref: 'ghcr.io/${{ github.repository_owner }}/website:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
      with:
        sarif_file: 'trivy-results.sarif'