name: Scan with Trivy

on:
  workflow_run:
    workflows: ["Build and Push to Docker Hub"]
    types:
      - completed

jobs:
  scan:
    name: Scan Images

    permissions:
      security-events: write
      packages: read

    runs-on: ubuntu-latest
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@c03d123cb480c08c69b054af418ea5e69fe6e57e # master
      with:
        image-ref: 'ghcr.io/${{ github.repository_owner }}/website:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d # v4
      with:
        sarif_file: 'trivy-results.sarif'